Squashed 'rengine/' changes from 8307cfc..4c2e1bf
4c2e1bf [add] Support for Backspace, Delete and '*/-+.'
78c5d16 [add] AText.setText && AText.getText
3ac63cf [~] Update github action
a593137 [~] add install of nohamm/json
4aeeaec [~] Update install script to check connan profile and return error if not exist
921184c [~] update test script
c3ddd62 [~] Update folder name from 'githubs' from 'github'
fb74787 Merge branch 'game_engine-dev' of github.com:Julian52575/R-Type into game_engine-dev
68263e7 [~+] Update unit test script and add github action for release and dev
0ab8540 [fix] compile.sh using lib rengine_graphics_sfml
bbf399a Merge branch 'game_engine-dev' of github.com:Julian52575/R-Type into game_engine-dev
2b45a45 [~] FIx crash and change handle of client in list
a5bab95 Merge branch 'game_engine-dev' of github.com:Xekko1629/R-Type into game_engine-dev
206d7ab [add] Registry.clear + .removeComponent && ECS.clearEntities + .clearComponents
caf96c4 [fix] Added precision for non-active in Entity.int()
3b9ece6 [ADD] rengine server library
eaa8688 Merge branch 'game_engine-dev' of github.com:Julian52575/R-Type into game_engine-dev
58c5221 [ADD] divide rengine into two library
345f7d9 Merge branch 'game_engine-dev' of github.com:Julian52575/R-Type into game_engine-dev
61de310 [+] New lib network with tcp and udp and split client and server hpp
615e874 [fix] SFMLSprite resetting scale on flip()
75a56f6 [add] example folder
4ebd900 [add] ASprite.flip() && fix UserInputTypeNA when processing KeyboardChar on SFMLWindow
ee61742 [add] ASprite.rotate
99cd537 [add] Improve exception && exception message in SparseArray []
6a54edc [add] Sound management
b067086 [add] Text in GraphicManager && Improved doxygen comments && added __ at the start of lib define
bc584f6 [fix] Added some doxygen style comment
6c0e50d [add] Circle and Rectangle sprite type in SpriteSpecs
f1c58b3 [fix] Lowercase letter if no shift is pressed on events
1319852 [add] UserInputManager.receivedInput(UserInputType)
785685a [add] UserInputManager.receivedInput && unit tests
10e337d [fix] Using sf::Keyboard::isKeyPressed instead of damn worthless sf::Event for keyboard input
4ba186c [fix] Error 'Trying to access the pixels of an empty image' on default SFMLWindow
0d6e243 [fix] Init window with default value in getWindow if it wasn't created previously
ef0938c [fix] Remove std::endl in operator<<
20dee12 [add] rng function
adba899 [add] Type name in ECSExceptionNoComponentFunction
6fcc117 [fix] Separated window creation in createWindow() method instead of constructor
49f177e [fix] undefined reference to typeinfo for Rengine::Graphics::AWindow'
a1b83e9 [add] methods ECS.getEntityLimit() && ECS.getActiveEntitiesCount()
26883ae [add] Deltatime related method in Window
206a522 [fix] Remove const qualifier for ECS& in Component function
cc42c6e [fix] Removed exception in ECS.registerComponent()'s doxygen comment
e0700c3 [add] ECS.removeEntity(size_type) && GraphicManagerSingletone
2d970b1 Merge pull request #16 from Julian52575/devTools
565d5e7 [fix] Enabled build/include_what_you_use back
77e59ef [fix] Enable include order back && disable error on relative include path
b175c88 [add] Method Entity.getComponentNoExcept
bdb4d41 [fix] Setting scale independently of animation
457463b Merge pull request #13 from Julian52575/game_engine-rulianrework
8b51ef3 [fix] optional animation in SpriteSpecs && floating point exception in SFMLSprite.advanceFrameFromTime
5d541bf [fix] inline createNewElement && return reference in get
019e214 [add] Custom parameters in componentFunction
a7afe44 Merge branch 'game_engine-rulianrework' of github.com:Xekko1629/R-Type into game_engine-rulianrework
b2aabb5 [add] Constructing with default values
f7fabcc [fix] ajouter z dans print vector z
2e08a8c [fix] setting SFMLWindow background color depending on WindowSpecs && Capped WindowSpecs.backgroundColor to 255
f30b3da [fix] Linter error #1
REVERT: 8307cfc Merge pull request #12 from Julian52575/game_engine-dev

git-subtree-dir: rengine
git-subtree-split: 4c2e1bf1851468863e824626e1cb9125eb459146